### ISSUE TITLE
Only authorized users should be able to access the metadata form

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/ckanext-dcat_usmetadata#25]
## Acceptance criteria

- [ ] When I am **not logged in** as an authorized user (e.g., sysadmin or a member of an organization where I have rights to add/edit datasets)
- [ ] and I visit the /dataset/new-metadata
- [ ] or click on the `Add Dataset` button located on the Datasets page **and** _any_ organization page 
- [ ] Then I get an access denied message

## Tasks

Add check_access to new metadata path in CKAN

- [ ] Update ckan controller in dcat-usmetadata to do check_access for admin

**Comment by anuveyatsu** [comment]
This should be resolved once we properly implement https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/424

**Comment by anuveyatsu** [comment]
@osahon-okungbowa @starsinmypockets I believe this should be now resolved.

**Comment by adborden** [comment]
Can we clarify? The form should be accessible to any logged in users, not admins. Any editor user can add datasets to their own organization through this form, just like in the built-in CKAN dataset form.

**Comment by anuveyatsu** [comment]
@adborden yes, exactly. I think the issue description is a bit misleading. I'll now update the title and descriptions of this issue.

**Comment by osahon-okungbowa** [comment]
@anuveyatsu  This issue was not tackled in #424 https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/424

NOTE: our implementation should support (be compatible with) CKAN 2.5 and CKAN 2.8+. 
Maybe use an if/switch statement to check the version of CKAN being run and implement accordingly?
