### ISSUE TITLE
Consolidate package.json and metadata-app/package.json

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#83]
In order to simplify development workflow and maintain conventions with other Data.gov projects, Data.gov developers want the metadata-app/package.json file consolidated into a single top-level package.json.

## Acceptance criteria 
- [ ] There is one only top-level package.json
- [ ] I can run React app from top-level package.json
- [ ] I can run tests of React app from top-level package.json

## Tasks 
- [x] Eject React app
- [x] Move all React related scripts and config into the root fodler
- [x] Move and adjust the scripts from _metadata-app/package.json_ into _./package.json_
- [x] Update CI configs according to the new changes
- [x] Update README accordingly

**Comment by anuveyatsu** [comment]
@adborden there 2 `package.json` files because we basically have 2 node packages:

1. The React app which is located in `metadata-app` directory
2. The integration tests which is part of the CKAN extension. This one is used only for cypress related tests.

**Comment by adborden** [comment]
Right, why can't we combine them into one top-level package.json?

You say the top level one is only used for cypress related tests, but some of the scripts `cd` into metadata-app for building anyway, so it kind of seems like there is not a clear distinction between them. I don't really see why you're treating them as two separate packages. One couldn't exist without the other, correct?

**Comment by anuveyatsu** [comment]
@adborden yes, we can combine them for sure. I'm only pointing out why we have 2 separate `package.json` files. I'd say that there are 2 separate apps, **the React app** that could work outside of CKAN as a separate service (eg, if we move towards microservices) and **the CKAN extension** that alters CKAN's templates and imports JS modules (the react app). The second `package.json` (in root directory) is used for testing the extension's behaviour. We could consolidate it into `/metadata-app/package.json` with a clear note about how that integration tests work in the `README.md`.

**Comment by adborden** [comment]
Ah, right, I shouldn't have phrased this issue as a question. Right now we're not using microservices and have no plans to move the React app into it's own service. This ticket is about consolidating into a single top-level package.json. Sorry I wasn't clear.

In general our projects work from the top-level directory--I don't think developers should have to cd into specific directories for development unless there's a good reason to. I think this also simplifies editor configurations (open your editor at the top level and that's the environment your editor should be activating for node_modules, python deps, linter configs, etc).
