### ISSUE TITLE
Consistent task running

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#84]
README refers to `make`, `yarn`, and `npx`. Can we consolidate so that all commands are either in the Makefile or in package.json?

## Acceptance criteria

* [x] I can run all scripts using single way, e.g., `yarn` commands.

## Tasks

* [x] Transfer all `make` scripts to `package.json`
* [x] Refactor CI commands and the `README.md` accordingly
