### ISSUE TITLE
`make test` does requires docker to be setup

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#85]
README describes testing instructions as `make test`, but when I run this I get an error:

```
$ make test
docker-compose exec ckan /bin/bash -c "nosetests --ckan --with-pylons=/srv/app/src_extensions/dcat_usmetadata/docker_test.ini src_extensions/dcat_usmetadata/"
ERROR: No such service: ckan
make: *** [test] Error 1
```

## Acceptance criteria

* [x] When I run `make test` it runs the CKAN extension tests without errors.
* [x] The CKAN extension tests are ran in the CI

## Tasks

* [x] Make sure that `make test` runs build command first so that docker is setup
* [x] Fix make test command
* [x] Fix CI to tun this tests

**Comment by adborden** [comment]
... Also, make test is commented out in CI.

**Comment by adborden** [comment]
`yarn test` looks good, thanks!
