### ISSUE TITLE
Unit tests hang with an open handle warning

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#93]
The tests take 5.35s, but there looks like an open handle that keeps jest running. After a 30 second timeout the handle is forcibly closed. This usually represents a bug in our code (not closing something or cleaning up a connection).

```
$ yarn test --all --watchAll=false
...
Test Suites: 13 passed, 13 total
Tests:       19 passed, 19 total
Snapshots:   4 passed, 4 total
Time:        5.35s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
✨  Done in 35.98s.
```

## Tasks
- [x] Troubleshoot the issue
- [ ] ~~implement solution to fix the issue~~
- [x] Update README for running unit tests

## Acceptance criteria
- [ ] Once the tests passed close handles

**Comment by kmanaseryan** [comment]
@adborden I think this has already got fixed unintentionally during our last PRs, because now when I run Jest tests I don't get this error any more.

**Comment by kmanaseryan** [comment]
@adborden created #127 to update REAME for the unit tests.

**Comment by adborden** [comment]
I'm still seeing the error:
```
$ yarn test:metadata-app
Test Suites: 14 passed, 14 total
Tests:       26 passed, 26 total
Snapshots:   4 passed, 4 total
Time:        10.66s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
✨  Done in 42.08s.
```

`yarn test:metadata-app --detectOpenHandles` did not give any clues.

**Comment by kmanaseryan** [comment]
hello @adborden. I and Anu have tested this again from our end and we cannot reproduce the error. Maybe we can pair on this today?

**Comment by adborden** [comment]
This seems to have resolved itself.
