### ISSUE TITLE
"Failed prop type: checker is not a function" in ResourceUpload test

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#94]
When running unit tests, the following error is logged into stdout:

```
 PASS  src/components/ResourceUpload/index.test.js
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: checker is not a function
          in ResourceUpload (at ResourceUpload/index.test.js:11)
          in Formik (at ResourceUpload/index.test.js:8)
          in Form (at ResourceUpload/index.test.js:18)
```

Note that the tests are successfully passed but the error log is confusing.

## Acceptance criteria

* [ ] No errors are logged when running the tests

## Tasks

* [x] Investigate why this is happening
  * [x] Go through findings from analysis section
    * [x] If any of the links are relevant, apply the fix
    * [ ] ~If not, do further investigation~
* [x] Deploy/push the fix (eg, PR)

## Analysis

Quick googling:

https://stackoverflow.com/questions/29995444/react-checker-is-not-a-function
https://stackoverflow.com/questions/39794219/react-warning-failed-prop-type-checker-is-not-a-function
https://stackoverflow.com/questions/40874861/react-proptype-with-two-possible-shapes
